// lib/graph/planner/node.ts
import { llm } from "../llm";
import { VentureStateType } from "../state";
import { ResearchPlannerOutputSchema } from "./schema";
import { PLANNER_PROMPT } from "./prompt";
import { ResearchPlannerOutput } from "./types";

export async function researchPlannerAgent(state: VentureStateType) {
  console.log("--- Agent: Research Planner ---");

  const ventureContext = state.ventureContext;
  if (!ventureContext) {
    console.warn("No ventureContext found in state! Falling back.");
    return {
      researchPlan: [],
    };
  }

  console.log(`Planning research for: "${ventureContext.goal}"`);

  try {
    const structuredLlm = llm.withStructuredOutput(ResearchPlannerOutputSchema);

    // Format the prompt with the structured context JSON
    const prompt = PLANNER_PROMPT.replace(
      "{ventureContext}",
      JSON.stringify(ventureContext, null, 2)
    );

    const result = (await structuredLlm.invoke(prompt)) as ResearchPlannerOutput;
    if (!result || !result.research_dimensions || !result.search_queries) {
      throw new Error("Invalid or empty research planner output received from LLM");
    }

    console.log(`Research Objective: ${result.research_objective}`);
    console.log(`Research Depth: ${result.research_depth}`);

    // Collect all queries generated by the planner for active dimensions
    const planQueries: string[] = [];
    const dims = result.research_dimensions || {};
    const sq = result.search_queries || {};

    const cleanString = (val: any): string => {
      if (typeof val === "string") return val;
      if (val && typeof val === "object") {
        return val.query || val.text || val.question || JSON.stringify(val);
      }
      return String(val || "");
    };

    const addQueries = (queryList: any) => {
      if (Array.isArray(queryList)) {
        for (const q of queryList) {
          const str = cleanString(q).trim();
          if (str) planQueries.push(str);
        }
      } else if (typeof queryList === "string" && queryList.trim()) {
        planQueries.push(queryList.trim());
      }
    };

    if (dims.market && sq.market) addQueries(sq.market);
    if (dims.competition && sq.competition) addQueries(sq.competition);
    if (dims.customers && sq.customers) addQueries(sq.customers);
    if (dims.regulations && sq.regulations) addQueries(sq.regulations);
    if (dims.finance && sq.finance) addQueries(sq.finance);
    if (dims.funding && sq.funding) addQueries(sq.funding);
    if (dims.technology && sq.technology) addQueries(sq.technology);
    if (dims.operations && sq.operations) addQueries(sq.operations);

    // Fallback if no queries were generated
    if (planQueries.length === 0) {
      console.warn("Planner generated 0 queries. Falling back to default goal query.");
      const goalStr = cleanString(ventureContext.goal) || "venture business opportunity";
      planQueries.push(`${goalStr} market size`);
    }

    console.log(`Planned ${planQueries.length} total search queries.`);

    return {
      // We overwrite or append to researchPlan. Since reducer is append, we can overwrite it by returning it.
      // Wait, reducer in state.ts is a reducer: (a, b) => [...a, ...b]. So returning it will append.
      // That's fine, it will combine with previous or replace.
      researchPlan: planQueries,
      researchPlanDetails: result,
      finalReport: {
        ...state.finalReport,
        researchObjective: result.research_objective,
        researchDepth: result.research_depth,
        researchPlanDetails: result,
      },
    };
  } catch (error: any) {
    console.error("Research Planner Agent Error:", error);

    // Fallback structure in case of failure
    const fallbackPlan: ResearchPlannerOutput = {
      research_objective: `Research the market and viability for: ${ventureContext.goal}`,
      research_depth: "MEDIUM",
      research_dimensions: {
        market: true,
        competition: true,
        customers: true,
        regulations: false,
        finance: false,
        funding: false,
        technology: false,
        operations: false,
      },
      search_queries: {
        market: [`${ventureContext.goal} market size trends`],
        competition: [`${ventureContext.goal} main competitors`],
        customers: [`${ventureContext.goal} customer pain points`],
        regulations: [],
        finance: [],
        funding: [],
        technology: [],
        operations: [],
      },
      source_priorities: [
        {
          source_type: "Industry Reports",
          priority: 1,
          reason: "Default backup priority",
        },
      ],
      risk_focus_areas: ["Market viability"],
      critical_unknowns: ["Customer adoption rate"],
    };

    return {
      researchPlan: [
        ...fallbackPlan.search_queries.market,
        ...fallbackPlan.search_queries.competition,
        ...fallbackPlan.search_queries.customers,
      ],
      researchPlanDetails: fallbackPlan,
    };
  }
}
