"use client";
import ProjectGuard from "@/components/ProjectGuard";
import DashboardLayout from "@/components/DashboardLayout";
import { motion } from "framer-motion";
import { useProjectStore } from "@/store/useProjectStore";
import {
  AreaChart, Area, XAxis, YAxis, Tooltip, ResponsiveContainer,
  BarChart, Bar, Cell,
} from "recharts";

const marketGrowth = [
  { year: "2024", value: 1.2 }, { year: "2025", value: 1.6 }, { year: "2026", value: 2.1 },
  { year: "2027", value: 2.8 }, { year: "2028", value: 3.6 }, { year: "2029", value: 4.5 },
  { year: "2030", value: 5.6 },
];

const segments = [
  { name: "Fleet Operators", value: 38, color: "#daf264" },
  { name: "Individual EV Owners", value: 29, color: "#c8e84a" },
  { name: "Charging Infrastructure", value: 21, color: "#7ab010" },
  { name: "Software / SaaS", value: 12, color: "#4a7a00" },
];

const geographies = [
  { region: "India (Primary)", opportunity: 92 },
  { region: "Southeast Asia",  opportunity: 78 },
  { region: "Middle East",     opportunity: 65 },
  { region: "Europe",          opportunity: 55 },
];

const ACC = "#daf264";

export default function ResearchPage() {
  const { projects, activeId } = useProjectStore();
  const activeProject = projects.find((p) => p.id === activeId);

  const formatMarketValue = (val: any): string => {
    if (!val) return "";
    if (typeof val === "object") {
      return String(val.value || val.val || JSON.stringify(val));
    }
    return String(val);
  };

  const formatMarketDesc = (val: any): string => {
    if (!val) return "";
    if (typeof val === "object") {
      return String(val.description || val.value || val.val || JSON.stringify(val));
    }
    return String(val);
  };

  return (
    <ProjectGuard>
    <DashboardLayout>
      <div className="p-8 space-y-6">
        {/* Header */}
        <div className="flex items-center justify-between">
          <div>
            <div className="flex items-center gap-2 mb-1">
              <span className="text-lg" style={{ color: ACC }}>◎</span>
              <span className="text-xs font-medium px-2 py-0.5 rounded-full"
                style={{ background: "rgba(218, 242, 100, 0.1)", color: ACC }}>Market Research Agent · Done</span>
            </div>
            <h1 className="text-2xl font-bold text-white">Market Analysis Report</h1>
            <p className="text-sm mt-1" style={{ color: "var(--muted-fg)" }}>
              {activeProject?.name || "EV Startup Platform"} · {activeProject?.description ? activeProject.description.slice(0, 60) + "..." : "India Market"} · Generated by AI
            </p>
          </div>
          <div className="flex gap-2">
            <button className="text-xs px-3 py-2 rounded-lg font-medium"
              style={{ background: "var(--card-bg)", color: "var(--muted-fg)", border: "1px solid var(--card-border)" }}>
              ↓ Export PDF
            </button>
            <button className="text-xs px-3 py-2 rounded-lg font-medium"
              style={{ background: "var(--accent)", color: "#0a0a0a" }}>
              ⟳ Re-run Agent
            </button>
          </div>
        </div>

        {/* Dynamic AI Summary section */}
        {activeProject?.finalReport?.summary && (
          <div className="rounded-xl p-5" style={{ background: "rgba(218, 242, 100, 0.05)", border: "1px solid rgba(218, 242, 100, 0.2)" }}>
            <h3 className="font-semibold text-sm text-white mb-2">Executive Summary (Generated by Intent Agent)</h3>
            <p className="text-sm leading-relaxed" style={{ color: "var(--muted-fg)" }}>
              {activeProject.finalReport.summary}
            </p>
          </div>
        )}

        {/* Dynamic AI Research section */}
        {activeProject?.marketIntel?.rawResearch && (
          <div className="rounded-xl p-5" style={{ background: "var(--card-bg)", border: "1px solid var(--card-border)" }}>
            <h3 className="font-semibold text-sm text-white mb-2">Live Web Search (Generated by Research Agent)</h3>
            <div className="text-xs space-y-2 max-h-96 overflow-y-auto pr-2" style={{ color: "var(--muted-fg)" }}>
              <pre className="whitespace-pre-wrap font-sans leading-relaxed">
                {typeof activeProject.marketIntel.rawResearch === 'string' 
                  ? activeProject.marketIntel.rawResearch 
                  : JSON.stringify(activeProject.marketIntel.rawResearch, null, 2)}
              </pre>
            </div>
          </div>
        )}

        {/* TAM / SAM / SOM — wired to marketIntel */}
        <div className="grid grid-cols-3 gap-4">
          {[
            {
              label: "TAM", sub: "Total Addressable Market",
              value: formatMarketValue(activeProject?.marketIntel?.marketSize?.tam || activeProject?.marketIntel?.tam || "$2.4T"),
              desc: formatMarketDesc(activeProject?.marketIntel?.marketSize?.tamDescription || "Global market by 2030"),
              pct: 100
            },
            {
              label: "SAM", sub: "Serviceable Addressable Market",
              value: formatMarketValue(activeProject?.marketIntel?.marketSize?.sam || activeProject?.marketIntel?.sam || "$180B"),
              desc: formatMarketDesc(activeProject?.marketIntel?.marketSize?.samDescription || "Addressable segment in target region"),
              pct: activeProject?.marketIntel?.marketSize?.samPct || 7.5
            },
            {
              label: "SOM", sub: "Serviceable Obtainable Market",
              value: formatMarketValue(activeProject?.marketIntel?.marketSize?.som || activeProject?.marketIntel?.som || "$4.2B"),
              desc: formatMarketDesc(activeProject?.marketIntel?.marketSize?.somDescription || "5-year target capture"),
              pct: activeProject?.marketIntel?.marketSize?.somPct || 0.17
            },
          ].map((item) => (
            <motion.div key={item.label} whileHover={{ y: -2 }}
              className="rounded-xl p-5"
              style={{ background: "var(--card-bg)", border: "1px solid var(--card-border)" }}>
              <div className="flex items-center justify-between mb-1">
                <span className="text-xs font-semibold px-2 py-0.5 rounded-full"
                  style={{ background: "rgba(218, 242, 100, 0.1)", color: ACC }}>{item.label}</span>
                <span className="text-xs" style={{ color: "var(--muted-fg)" }}>{item.pct}%</span>
              </div>
              <p className="text-3xl font-bold text-white mt-2">{item.value}</p>
              <p className="text-xs font-medium mt-0.5" style={{ color: ACC }}>{item.sub}</p>
              <p className="text-xs mt-2 leading-relaxed" style={{ color: "var(--muted-fg)" }}>{item.desc}</p>
            </motion.div>
          ))}
        </div>

        {/* Market growth chart + segments */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
          <div className="rounded-xl p-5" style={{ background: "var(--card-bg)", border: "1px solid var(--card-border)" }}>
            <h3 className="font-semibold text-sm text-white mb-1">Market Growth Trajectory</h3>
            <p className="text-xs mb-4" style={{ color: "var(--muted-fg)" }}>Global EV market size ($T) · 2024–2030</p>
            <ResponsiveContainer width="100%" height={180}>
              <AreaChart data={marketGrowth}>
                <defs>
                  <linearGradient id="mg" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="0%" stopColor={ACC} stopOpacity={0.25} />
                    <stop offset="100%" stopColor={ACC} stopOpacity={0} />
                  </linearGradient>
                </defs>
                <XAxis dataKey="year" tick={{ fontSize: 10, fill: "#555" }} axisLine={false} tickLine={false} />
                <YAxis tick={{ fontSize: 10, fill: "#555" }} axisLine={false} tickLine={false} width={28} />
                <Tooltip contentStyle={{ background: "#1a1a1a", border: "1px solid #2a2a2a", borderRadius: 8, fontSize: 11 }}
                  formatter={(v: number) => [`$${v}T`]} />
                <Area type="monotone" dataKey="value" stroke={ACC} strokeWidth={2} fill="url(#mg)" dot={false} />
              </AreaChart>
            </ResponsiveContainer>
          </div>

          <div className="rounded-xl p-5" style={{ background: "var(--card-bg)", border: "1px solid var(--card-border)" }}>
            <h3 className="font-semibold text-sm text-white mb-1">Customer Segments</h3>
            <p className="text-xs mb-4" style={{ color: "var(--muted-fg)" }}>Market share by segment</p>
            <ResponsiveContainer width="100%" height={180}>
              <BarChart data={segments} layout="vertical" margin={{ left: -8 }}>
                <XAxis type="number" tick={{ fontSize: 9, fill: "#555" }} axisLine={false} tickLine={false} />
                <YAxis dataKey="name" type="category" tick={{ fontSize: 10, fill: "#888" }} axisLine={false} tickLine={false} width={140} />
                <Tooltip contentStyle={{ background: "#1a1a1a", border: "1px solid #2a2a2a", borderRadius: 8, fontSize: 11 }}
                  formatter={(v: number) => [`${v}%`]} />
                <Bar dataKey="value" radius={[0, 4, 4, 0]}>
                  {segments.map((s, i) => <Cell key={i} fill={s.color} />)}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Geographic opportunities */}
        <div className="rounded-xl p-5" style={{ background: "var(--card-bg)", border: "1px solid var(--card-border)" }}>
          <h3 className="font-semibold text-sm text-white mb-4">Geographic Opportunity Score</h3>
          <div className="space-y-3">
            {geographies.map((g) => (
              <div key={g.region}>
                <div className="flex justify-between text-xs mb-1">
                  <span className="text-white">{g.region}</span>
                  <span style={{ color: ACC }}>{g.opportunity}/100</span>
                </div>
                <div className="w-full h-2 rounded-full overflow-hidden" style={{ background: "var(--muted)" }}>
                  <motion.div className="h-full rounded-full"
                    initial={{ width: 0 }} animate={{ width: `${g.opportunity}%` }}
                    transition={{ duration: 0.8, ease: "easeOut" }}
                    style={{ background: "var(--accent)" }} />
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Key insights */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {[
            { title: "Key Trend", body: "India's EV market is growing at 49% CAGR, driven by government FAME-II subsidies and rising fuel costs. Charging infrastructure is the #1 bottleneck.", icon: "↑" },
            { title: "Opportunity Window", body: "Less than 3% of India's 5M+ EV owners have access to reliable charging management software. First-mover advantage is available now.", icon: "◎" },
          ].map((insight) => (
            <div key={insight.title} className="rounded-xl p-5 flex gap-4"
              style={{ background: "rgba(218, 242, 100, 0.04)", border: "1px solid rgba(218, 242, 100, 0.15)" }}>
              <div className="w-9 h-9 rounded-xl flex items-center justify-center text-lg flex-shrink-0"
                style={{ background: "rgba(218, 242, 100, 0.12)", color: ACC }}>
                {insight.icon}
              </div>
              <div>
                <p className="text-sm font-semibold text-white mb-1">{insight.title}</p>
                <p className="text-xs leading-relaxed" style={{ color: "var(--muted-fg)" }}>{insight.body}</p>
              </div>
            </div>
          ))}
        </div>

        {/* Research Plan — from researchPlan state */}
        {activeProject?.researchPlan && Array.isArray(activeProject.researchPlan) && activeProject.researchPlan.length > 0 && (
          <div className="rounded-xl p-5" style={{ background: "var(--card-bg)", border: "1px solid var(--card-border)" }}>
            <h3 className="font-semibold text-sm text-white mb-3 flex items-center gap-2">
              <span style={{ color: ACC }}>◈</span> Research Plan ({activeProject.researchPlan.length} queries)
            </h3>
            <div className="flex flex-wrap gap-2">
              {activeProject.researchPlan.map((q: string, i: number) => (
                <span key={i} className="text-xs px-2.5 py-1.5 rounded-lg"
                  style={{ background: "rgba(218, 242, 100, 0.06)", color: "var(--muted-fg)", border: "1px solid rgba(218, 242, 100, 0.1)" }}>
                  {q}
                </span>
              ))}
            </div>
          </div>
        )}

        {/* Evidence Sources — from evidence state */}
        {activeProject?.evidence && Array.isArray(activeProject.evidence) && activeProject.evidence.length > 0 && (
          <div className="rounded-xl p-5" style={{ background: "var(--card-bg)", border: "1px solid var(--card-border)" }}>
            <h3 className="font-semibold text-sm text-white mb-3 flex items-center gap-2">
              <span style={{ color: ACC }}>↗</span> Evidence Sources ({activeProject.evidence.length})
            </h3>
            <div className="space-y-2 max-h-64 overflow-y-auto pr-2">
              {activeProject.evidence.map((ev: any, i: number) => (
                <div key={i} className="rounded-lg p-3 flex items-start gap-3"
                  style={{ background: "var(--background)", border: "1px solid var(--card-border)" }}>
                  <span className="text-[10px] w-5 h-5 rounded flex items-center justify-center flex-shrink-0 mt-0.5"
                    style={{ background: "rgba(218, 242, 100, 0.1)", color: ACC }}>
                    {i + 1}
                  </span>
                  <div className="flex-1 min-w-0">
                    <p className="text-xs text-white font-medium truncate">
                      {ev && typeof ev === 'object' ? (ev.title || ev.query || `Source ${i + 1}`) : `Source ${i + 1}`}
                    </p>
                    <p className="text-[10px] mt-0.5 truncate" style={{ color: "var(--muted-fg)" }}>
                      {ev && typeof ev === 'object' ? (ev.url || ev.source || '') : (typeof ev === 'string' ? ev : '')}
                    </p>
                  </div>
                  {ev && typeof ev === 'object' && ev.credibilityScore != null && (
                    <span className="text-[10px] px-1.5 py-0.5 rounded flex-shrink-0"
                      style={{ background: ev.credibilityScore >= 0.8 ? "rgba(218,242,100,0.1)" : "rgba(245,158,11,0.1)",
                               color: ev.credibilityScore >= 0.8 ? ACC : "#fbbf24" }}>
                      {Math.round(ev.credibilityScore * 100)}%
                    </span>
                  )}
                </div>
              ))}
            </div>
          </div>
        )}
      </div>
    </DashboardLayout>
    </ProjectGuard>
  );
}
