import { PrismaClient } from '../src/generated/client';

const prisma = new PrismaClient();

const data = [
  {
    founderName: "Alex Chen",
    startupName: "NexusFlow AI",
    tagline: "Autonomous Data Engineering for Enterprise",
    category: "Data Infrastructure",
    stage: "Series A",
    traction: "$2.5M ARR, 45 Enterprise Customers including 3 Fortune 500s",
    mrr: "$200K",
    valuation: "$45M",
    targetAmount: "$12M",
    raisedAmount: "$4M",
    location: "San Francisco, CA",
    aboutQuote: "Eliminating manual data pipelines.",
    aboutText: "Former Head of Data at Stripe. 15 years experience in large-scale distributed systems.",
    problemText: "Data engineering teams spend 70% of their time on pipeline maintenance instead of driving insights.",
    solutionText: "Autonomous agents that self-heal data pipelines and auto-generate transformations.",
  },
  {
    founderName: "Sarah Jenkins",
    startupName: "MedSync",
    tagline: "AI-Powered Clinical Trial Matching",
    category: "HealthTech",
    stage: "Seed",
    traction: "Pilot with Mayo Clinic, 5,000 patients matched, $15k MRR",
    mrr: "$15K",
    valuation: "$15M",
    targetAmount: "$3M",
    raisedAmount: "$500K",
    location: "Boston, MA",
    aboutQuote: "Accelerating life-saving treatments.",
    aboutText: "MD/PhD from Harvard. Published 20+ papers on clinical trial optimization.",
    problemText: "80% of clinical trials are delayed due to patient enrollment issues.",
    solutionText: "NLP algorithms that instantly match patient EHRs with complex trial inclusion criteria.",
  },
  {
    founderName: "David Osei",
    startupName: "Lumiere Energy",
    tagline: "Optimized Grid Storage Management",
    category: "ClimateTech",
    stage: "Series B",
    traction: "$8M ARR, managing 500MWh of storage capacity",
    mrr: "$650K",
    valuation: "$120M",
    targetAmount: "$30M",
    raisedAmount: "$15M",
    location: "Austin, TX",
    aboutQuote: "Powering the renewable transition.",
    aboutText: "Ex-Tesla energy storage engineer. Designed battery management systems for Megapack.",
    problemText: "Renewable energy is intermittent, leading to grid instability and wasted power.",
    solutionText: "AI forecasting software that optimizes battery dispatch for maximum arbitrage and stability.",
  },
  {
    founderName: "Elena Rodriguez",
    startupName: "FinSight",
    tagline: "Real-time CFO Co-pilot",
    category: "FinTech",
    stage: "Seed",
    traction: "120 paying mid-market customers, $40k MRR",
    mrr: "$40K",
    valuation: "$20M",
    targetAmount: "$4M",
    raisedAmount: "$1.2M",
    location: "New York, NY",
    aboutQuote: "Financial clarity at the speed of thought.",
    aboutText: "Former Goldman Sachs VP. Built internal trading algorithms for 8 years.",
    problemText: "Mid-market CFOs rely on static spreadsheets that are out of date the moment they are exported.",
    solutionText: "Direct ERP integrations with LLM-driven query engines for instant financial modeling.",
  },
  {
    founderName: "Kenji Sato",
    startupName: "AeroInspect",
    tagline: "Drone-based Infrastructure Maintenance",
    category: "Robotics",
    stage: "Series A",
    traction: "Contracts with 5 major utilities, $1.2M ARR",
    mrr: "$100K",
    valuation: "$35M",
    targetAmount: "$8M",
    raisedAmount: "$3M",
    location: "Seattle, WA",
    aboutQuote: "Making infrastructure safe again.",
    aboutText: "PhD in Robotics from CMU. Previously led perception teams at Amazon Prime Air.",
    problemText: "Manual inspection of bridges and power lines is dangerous, slow, and expensive.",
    solutionText: "Autonomous drone fleets with edge AI that detects micro-fractures in real-time.",
  },
  {
    founderName: "Aisha Patel",
    startupName: "OmniRetail",
    tagline: "Unified Inventory Intelligence",
    category: "RetailTech",
    stage: "Seed",
    traction: "Deployed in 400 stores, $25k MRR",
    mrr: "$25K",
    valuation: "$18M",
    targetAmount: "$2.5M",
    raisedAmount: "$800K",
    location: "Chicago, IL",
    aboutQuote: "The operating system for modern retail.",
    aboutText: "Ex-Walmart supply chain director. Specialized in inventory optimization algorithms.",
    problemText: "Omnichannel retailers suffer from a 15% discrepancy between digital and physical inventory.",
    solutionText: "Computer vision and RFID fusion for 99.9% accurate real-time inventory tracking.",
  },
  {
    founderName: "Marcus Thorne",
    startupName: "CyberShield AI",
    tagline: "Zero-Day Threat Neutralization",
    category: "Cybersecurity",
    stage: "Series A",
    traction: "$3M ARR, protecting 1M+ endpoints",
    mrr: "$250K",
    valuation: "$60M",
    targetAmount: "$15M",
    raisedAmount: "$6M",
    location: "Tel Aviv, Israel",
    aboutQuote: "Proactive defense for the digital age.",
    aboutText: "Former Unit 8200 cyber warfare specialist. Holds 5 patents in malware detection.",
    problemText: "Traditional antivirus relies on known signatures, failing against novel zero-day attacks.",
    solutionText: "Behavioral AI models that sandbox and neutralize anomalous execution patterns instantly.",
  },
  {
    founderName: "Chloe Dubois",
    startupName: "AgriYield",
    tagline: "Precision Agriculture via Satellite",
    category: "AgTech",
    stage: "Seed",
    traction: "Monitoring 2M acres, $50k MRR",
    mrr: "$50K",
    valuation: "$22M",
    targetAmount: "$5M",
    raisedAmount: "$1.5M",
    location: "Denver, CO",
    aboutQuote: "Feeding the world efficiently.",
    aboutText: "Agronomist and data scientist. Spent 5 years at John Deere developing precision tech.",
    problemText: "Farmers over-apply fertilizer by 30%, increasing costs and environmental runoff.",
    solutionText: "Hyperspectral satellite imagery analysis to map nutrient deficiencies at the meter level.",
  },
  {
    founderName: "James Wilson",
    startupName: "LegalMind",
    tagline: "AI Associate for Law Firms",
    category: "LegalTech",
    stage: "Pre-Seed",
    traction: "3 closed beta pilots with AmLaw 100 firms",
    mrr: "$5K",
    valuation: "$8M",
    targetAmount: "$1.5M",
    raisedAmount: "$200K",
    location: "London, UK",
    aboutQuote: "Automating legal grunt work.",
    aboutText: "Former corporate lawyer turned self-taught ML engineer.",
    problemText: "Junior associates spend hundreds of billable hours on mundane document review.",
    solutionText: "Specialized LLMs trained on case law to draft briefs and review contracts 10x faster.",
  },
  {
    founderName: "Priya Sharma",
    startupName: "Edaptive",
    tagline: "Personalized K-12 Tutoring",
    category: "EdTech",
    stage: "Series A",
    traction: "50,000 active students, $1.5M ARR",
    mrr: "$125K",
    valuation: "$40M",
    targetAmount: "$10M",
    raisedAmount: "$4.5M",
    location: "Toronto, Canada",
    aboutQuote: "Unlocking every student's potential.",
    aboutText: "PhD in Cognitive Science. Former curriculum designer for Pearson.",
    problemText: "A 1-to-30 teacher-student ratio leaves behind students who need specialized pacing.",
    solutionText: "Generative AI tutors that adapt learning paths based on real-time comprehension metrics.",
  },
  {
    founderName: "Michael Chang",
    startupName: "FreightOS",
    tagline: "Autonomous Logistics Routing",
    category: "Logistics",
    stage: "Series B",
    traction: "$12M ARR, routing 10k trucks daily",
    mrr: "$1M",
    valuation: "$150M",
    targetAmount: "$40M",
    raisedAmount: "$25M",
    location: "Atlanta, GA",
    aboutQuote: "The brain of the global supply chain.",
    aboutText: "Ex-Uber freight lead engineer. Built matching algorithms handling $1B+ in GMV.",
    problemText: "20% of trucking miles are driven empty, costing the industry billions.",
    solutionText: "Dynamic matching algorithms that backhaul freight and optimize routes in real-time.",
  },
  {
    founderName: "Sofia Rossi",
    startupName: "BioPrint",
    tagline: "3D Printed Synthetic Organs",
    category: "BioTech",
    stage: "Series A",
    traction: "Successful animal trials, 3 patents granted",
    mrr: "$0",
    valuation: "$80M",
    targetAmount: "$20M",
    raisedAmount: "$12M",
    location: "San Diego, CA",
    aboutQuote: "Ending the transplant waiting list.",
    aboutText: "Pioneer in tissue engineering. Former researcher at the Salk Institute.",
    problemText: "100,000 people are waiting for organ transplants in the US alone.",
    solutionText: "Bioprinting vascularized tissues using patient-derived stem cells to eliminate rejection.",
  },
  {
    founderName: "Tom Baker",
    startupName: "ConstructAI",
    tagline: "Generative Design for Architects",
    category: "PropTech",
    stage: "Seed",
    traction: "20 architectural firms onboarded, $30k MRR",
    mrr: "$30K",
    valuation: "$15M",
    targetAmount: "$3M",
    raisedAmount: "$1M",
    location: "Berlin, Germany",
    aboutQuote: "Designing the cities of tomorrow.",
    aboutText: "Architect and software engineer. Worked at Foster + Partners on algorithmic design.",
    problemText: "Conceptual design and structural feasibility studies take months of manual drafting.",
    solutionText: "AI that generates optimized floor plans and structural models from text prompts.",
  },
  {
    founderName: "Nina Patel",
    startupName: "QuantumSecure",
    tagline: "Post-Quantum Cryptography",
    category: "DeepTech",
    stage: "Seed",
    traction: "2 POCs with major banks",
    mrr: "$0",
    valuation: "$25M",
    targetAmount: "$6M",
    raisedAmount: "$2M",
    location: "Zurich, Switzerland",
    aboutQuote: "Securing data against tomorrow's computers.",
    aboutText: "PhD in Quantum Physics from ETH Zurich. Published foundational papers on lattice cryptography.",
    problemText: "Quantum computers will break RSA encryption within the next decade.",
    solutionText: "Lattice-based cryptographic protocols that are mathematically proven to resist quantum attacks.",
  },
  {
    founderName: "Luis Gomez",
    startupName: "Vocalize",
    tagline: "AI Voice Dubbing for Creators",
    category: "Media",
    stage: "Series A",
    traction: "Used by 1,000+ top YouTubers, $2M ARR",
    mrr: "$160K",
    valuation: "$50M",
    targetAmount: "$12M",
    raisedAmount: "$5M",
    location: "Los Angeles, CA",
    aboutQuote: "Making content universally accessible.",
    aboutText: "Audio engineer and ML researcher. Previously at Spotify.",
    problemText: "Dubbing content into multiple languages is expensive, slow, and sounds unnatural.",
    solutionText: "Zero-shot voice cloning and lip-sync AI that dubs video while preserving the creator's emotion.",
  }
];

async function seed() {
  console.log("Seeding 15 startups...");
  for (const item of data) {
    // 1. Create Founder
    const founder = await prisma.founder.create({
      data: {
        fullName: item.founderName,
        email: item.founderName.toLowerCase().replace(' ', '.') + "@example.com",
        roleTitle: "Founder & CEO",
        aboutQuote: item.aboutQuote,
        aboutText: item.aboutText,
      }
    });

    // 2. Create Startup
    const startup = await prisma.startup.create({
      data: {
        name: item.startupName,
        tagline: item.tagline,
        category: item.category,
        stage: item.stage,
        valuation: item.valuation,
        targetAmount: item.targetAmount,
        raisedAmount: item.raisedAmount,
        founder: item.founderName,
        location: item.location,
        traction: item.traction,
        mrr: item.mrr,
        problemText: item.problemText,
        solutionText: item.solutionText,
        founderId: founder.id,
      }
    });

    console.log(`Created ${startup.name}`);
  }
  console.log("Done seeding!");
}

seed().catch(e => {
  console.error(e);
  process.exit(1);
}).finally(async () => {
  await prisma.$disconnect();
});
